### ISSUE TITLE
Question: Is it possible to run with "Application.ReadWrite.OwnedBy" instead of "Application.ReadWrite.All"?

### ISSUE THREAD

**Issue by bendikp** [nais/azurerator#164]
First of all, thanks for making azurerator. We've been using it for a while and it works great.

To tighten the permissions granted to azurerator we tried giving the Azure AD Application `Application.ReadWrite.OwnedBy` instead of `Application.ReadWrite.All`. `Application.ReadWrite.OwnedBy` seems to give azurerator the same permissions as `Application.ReadWrite.All`, but only for the Azure Ad Applications that azurerator owns, which seems like a smart thing. That did not work very well, and azurerator reported `registering application: 403 Forbidden:`.

Do you guys know why `Application.ReadWrite.OwnedBy` isn't sufficient to run azurerator?

**Comment by tronghn** [comment]
Hey there. Preliminary testing shows that this is due to the Graph API not allowing us to _create_ an application with the `acceptMappedClaims` property enabled while holding the `Application.ReadWrite.OwnedBy` permission.

However, we are able _update_ the application afterwards to configure the same property. Likely an oversight from Microsoft, as we've seen reports of terraform providers having the same issue. 

Then again, the property is only relevant if you're using claims-mapping policies, so we'll probably move to only enabling it if that feature flag is enabled.

We'll also have to make sure that the principal used by Azurerator is configured as an owner of all the managed applications, which we've observed is not always the case in our own tenants. Have you seen anything like this in your own tenant(s)?

**Comment by bendikp** [comment]
We see the same in our tenants. Some applications are owned by  azurerator, and some don't. Without any clear pattern on when an application get an owner or not.

**Comment by tronghn** [comment]
Apologies for the late follow-up. We've added a workaround to enable Azurerator to function with just the `Application.ReadWrite.OwnedBy` permission. 

We now also explicitly assign the authenticated principal (the service principal used by Azurerator) as an owner of both the Applications and Service Principals on creation. 

It will attempt to assign ownership on updates if the principal isn't an owner of the resources, though this will naturally fail if the principal only has the `Application.ReadWrite.OwnedBy` permission. A workaround in that case is either assigning ownership or temporarily granting the `Application.ReadWrite.All` permission.

**Comment by bendikp** [comment]
Thanks, we'll take it for a spin.
